### ISSUE TITLE
Space on path name

### ISSUE THREAD

**Issue by B-greg** [masterlittle/SlackUploader#1]
Hi,
I try to upload a file on slack, but I have a space on my file path and the plugin crash.
There is my file path:
"/Users/Shared/Jenkins/Home/workspace/Prod\ AppName/app/build/outputs/apk/app-*"

And there is the result from jenkins log:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (26) couldn't open file "/Users/Shared/Jenkins/Home/workspace/Prod"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (26) couldn't open file "AppName/app/build/outputs/apk/app-dev-2.7.12.apk"

Should I escape my path name with specific option or its an issue with the plugin?

Thank you for your help.

**Comment by masterlittle** [comment]
It seems like the platform is ignoring the space in your file path. Did you try renaming the file path without any spaces?

**Comment by B-greg** [comment]
The file path is set by the jenkins project so i can't rename it.
My jenkins server is running on a mac os, do you this its because of the bash version of osx?

**Comment by masterlittle** [comment]
That should not be the issue. Frankly I developed the plugin in Mac so it should not be platform related problem. I'm pretty sure it's due to the file path having space as the plugin is treating the suffix and prefix as two different file paths. See if you can rename it in your machine on which the file is being stored. Or try redirecting the output to another path and then using that path in the plugin.

**Comment by masterlittle** [comment]
I hope that you found a workaround for your issue. Closing this

**Comment by B-greg** [comment]
I just rename my project without any space.
