### ISSUE TITLE
Unable to set a directory path to upload multiple build files

### ISSUE THREAD

**Issue by jbouzekri** [masterlittle/SlackUploader#3]
I have installed your plugin and configured it this way : 

token : oauth token generated using slack api
channel : #android
path: /var/lib/jenkins/workspace/myapp/app/build/outputs/apk/

This folder contains 2 APKs file per build I want to upload.

In the post build hook log, I have this : 

```
curl: (26) couldn't open file "app-debug.apk"
curl: (26) couldn't open file "app-release-unsigned.apk"
```

It works if I specify only one of these 2 files. However it would be great if you updated your bash script to make it detect that the path is a directory and that it should upload all the files found in this directory.

**Comment by masterlittle** [comment]
Use /var/lib/jenkins/workspace/myapp/app/build/outputs/apk/*.apk

**Comment by jbouzekri** [comment]
I feel so stupid :blush: ... Totally forgot about globbing. Thanks for pointing it out. It works fine.
