### ISSUE TITLE
Using plugin in groovy code

### ISSUE THREAD

**Issue by RomanGrekov** [masterlittle/SlackUploader#4]
Hi guys. I want to use this plugin in my Jenkins pipeline job. I have groovy code for job and want to send file to Slack from it. Please advice

**Comment by masterlittle** [comment]
The plugin is language agnostic. Just give your Slack token and the path to the file you wan to upload in the relevant fields. 
eg - /var/files/abc.png

**Comment by RomanGrekov** [comment]
Thank you for reply. But I mean that I want to use plugin not with web interface as usual and as it described in docs. I would like to trigger file sending from groovy code(pipeline job in Jenkins 2). As I know it is possible. I saw it in another plugins, like this:
step([$class: 'Mailer', notifyEveryUnstableBuild: true, recipients: 'bla@bla.com ',  sendToIndividuals: true])
May be I can run your plugin this way?

**Comment by masterlittle** [comment]
I haven't worked on this, so I can't say for sure if this will work. But please go ahead and give it a shot. I'm eager to see if it works.

**Comment by RomanGrekov** [comment]
Ok

**Comment by masterlittle** [comment]
Closing this

**Comment by stephanepechard** [comment]
@RomanGrekov did you manage to make it work? I'm currently trying to do the same thing.
If it works, it could be valuable to add how you did into the documentation.
